using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AudioManager : MonoBehaviour
{
   /* public static AudioManager Instance;

    public AudioSource musicSource;
    public AudioSource sfxSource;
    public AudioClip overworldMusic;
    public AudioClip caveMusic;
    public AudioClip[] variouSFX;
    // Start is called before the first frame update
    void Start()
    {
        music.clip = overworldMusic;
        musicSource.Play();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    /*void Awake()
    {
        if(Instance == null){
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }else Destroy(gameObject);
    }
    public void PlayMusicSFX(AudioClip clip)
    {
        sfxSource.clip = clip;
        sfxSource.Play();
    }
    public void PlayRandomSFX(params AudioClip[] clips)
    {
        variousSFX = clips;
        int index = Random.Range(0,variousSFX.length);
        sfxSource.PlayOneShot(variouSFX[inedx]);
    }*/
}
